### ISSUE TITLE
MyActivity.CollectionsItems.java

### ISSUE THREAD

**Issue by mbelsky** [v4ekmarev/RSSreader#3]
1. Почему класс public?
2. Почему у переменных опять отсутствует модификатор "private"?
3. Зачем "getRssItemArrayList()"?
4. Для чего явная инициализация полей при объявлении класса?
5. Зачем это "RSSItem rssItem;" в 77 строке, не понимаю.
6. Так ошибки обрабатывать нельзя – e.printStackTrace(). Ищем адекватное решение.
7. Строка 89 – а если у нас UTF-8/16.. ?
8. Все строковые переменные("<title>" ...) было бы неплохо вынести в константы класса.
9. Если всмотреться в код извлечения title/description, то это тупой копипаст, нужно решить эту проблему, например созданием метода.
10. Переменная rssItemArrayList должна быть локальной для метода doInBackground.
11. Наличие флага flagTitle в коде, мне определённо не нравится.
12. Код onPostExecute мне тоже дико не нравится. Async таск ничего не должен знать про адаптер.

Собственно, что нужно помимо выше написанного: вынести класс AsyncTask в отдельный файл и научиться пробрасывать результат из asyncTask в активити, без всяких ебучих public static variables. Ну и нормальное имя классу тоже было бы не плохо дать.

Много каких-то "невнимательностей", лишнего, неиспользуемого кода.

**Comment by v4ekmarev** [comment]
Решил задачу 8,9, по 11 я не знаю стоит ли вообще загоняться по этому поводу так как и так с парсингом все хреного, думал сделать по буквенный парсер, но передумал=), нашел метод с NodeList, но там тоже свои минусы, можно заюзать какую-нибуть либу, но стоит ли?, если настоишь чтоб я убрал флаг я что-нибуть придумаю, а так не вижу смысла. По кодировкам вопрос остается открытым я почитал про кодировки, но один хрен не понятно что делать и задача поставлена аля придумал что-то, что я хочу чтоб было, если в задаче требуется обрабатывать все кодировки то зачем? "Кодировок море, но на сегодняшний день для Рунета наиболее популярными являются кодировки windows-1251 и utf-8, и именно между этими кодировками стоит выбор пользователя при создании веб-странички."

**Comment by mbelsky** [comment]
* Зачем закомментил конструктор?
* https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListItemsTask.java#L50 Окей, случилась ошибка и ты вывел лог. Почему ты продолжаешь работу таски?
* https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListItemsTask.java#L64 опять мелочи
* 8 9 и 11 надо было делать, чтобы отучиться от дурного тона, а потом переделать это ещё раз и лучше, чтобы запомнилось в двойне.
* снова вопрос остался без ответа: https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListItemsTask.java#L92 а есди коллбек null?
* https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListItemsTask.java#L99 Уже писал, чтобы ты методы с большой буквы не именовал. Это тебе не C#.
* Зачем используешь Html.fromHtml в https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListItemsTask.java#L66 ?
