### ISSUE TITLE
BoxAdapter.java

### ISSUE THREAD

**Issue by mbelsky** [v4ekmarev/RSSreader#4]
Опять же – ебейшее название класса.
1. Не вижу private модификатора у членов класса.
2. Код getView достаточно ужасен и непроизводителен. Почитай про ViewHolder, разберись зачем оно.
3. Название для переменной типа "objects" расстраивает.

**Comment by v4ekmarev** [comment]
все вроде решено

**Comment by mbelsky** [comment]
ну в адаптере меня смущают только две вещи:
https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListAdapter.java#L45
опять смущают эти пустые строчки ну и метод
https://github.com/v4ekmarev/RSSreader/blob/master/src/com/vchekmarev/rssreader/ListAdapter.java#L66
достаточно сомнительная хрень.. зачем ты его сделал? ещё и getItem() внутри используешь
